approve:
- lgtm_acts_as_approve: true
  repos:
  - someorg/somerepo
  require_self_approval: true
cat: {}
cherry_pick_unapproved:
  branchregexp: ^release-.*$
  comment: |-
    This PR is not for the master branch but does not have the `cherry-pick-approved`  label. Adding the `do-not-merge/cherry-pick-not-approved`  label.

    To approve the cherry-pick, please assign the patch release manager for the release branch by writing `/assign @username` in a comment when ready.

    The list of patch release managers for each release can be found [here](https://git.k8s.io/sig-release/release-managers.md).
config_updater:
  gzip: false
  maps:
    env/prow/config.yaml:
      name: config
    env/prow/plugins.yaml:
      name: plugins
heart: {}
label:
  additional_labels: null
owners:
  labels_excludes:
  - approved
  - lgtm
plugins:
  someorg/somerepo:
  - config-updater
  - approve
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  - dog
  - pony
requiresig: {}
sigmention:
  regexp: (?m)@kubernetes/sig-([\w-]*)-(misc|test-failures|bugs|feature-requests|proposals|pr-reviews|api-reviews)
size:
  l: 0
  m: 0
  s: 0
  xl: 0
  xxl: 0
triggers:
- join_org_url: https://github.com/orgs/someorg/people
  repos:
  - someorg/somerepo
  - myorg/myowner
  trusted_org: someorg