branch-protection: {}
github:
  LinkURL: null
in_repo_config: {}
plank: {}
postsubmits:
  myorg/myowner:
  - agent: tekton-pipeline
    context: release
    name: release
presubmits:
  myorg/myowner:
  - agent: tekton-pipeline
    always_run: true
    context: lint
    name: lint
    rerun_command: /relint
    trigger: /lint
push_gateway:
  serve_metrics: false
tide:
  context_options:
    required-if-present-contexts: null