apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: lint
    context: "lint"
    always_run: true
    optional: false
    trigger: "/lint"
    rerun_command: "/relint"
    agent: tekton-pipeline
  postsubmits:
  - name: release
    context: "release"
    agent: tekton-pipeline
