apiVersion: tekton.dev/v1beta1
kind: PipelineRun
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml@versionStream
        steps:
        - name: jx-variables
        - name: build-npm-install
        - name: build-npm-test
        - name: build-container-build
        - name: promote-jx-preview
