kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhooks-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["foghornci.io"]
  resources: ["webhooks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
