branch-protection:
  orgs:
    jenkins-x:
      repos:
        bdd-jx:
          required_status_checks:
            contexts:
              - pr-build
    jstrachan:
      repos:
        environment-jstrachan-v1-production:
          required_status_checks:
            contexts:
              - promotion-build
        environment-jstrachan-v1-staging:
          required_status_checks:
            contexts:
              - promotion-build
        godemo25:
          required_status_checks:
            contexts:
              - pr-build
  protect-tested-repos: true
gerrit: {}
owners_dir_blacklist:
  default: null
  repos: null
plank: {}
pod_namespace: jx
postsubmits:
  jenkins-x/bdd-jx:
    - agent: tekton
      branches:
        - master
      context: ""
      name: release
  jstrachan/environment-jstrachan-v1-production:
    - agent: tekton
      branches:
        - master
      context: ""
      name: promotion
  jstrachan/environment-jstrachan-v1-staging:
    - agent: tekton
      branches:
        - master
      context: ""
      name: promotion
  jstrachan/godemo25:
    - agent: tekton
      branches:
        - master
      context: ""
      name: release
presubmits:
  jenkins-x/bdd-jx:
    - agent: tekton
      always_run: true
      context: pr-build
      name: pr-build
      rerun_command: /test this
      trigger: (?m)^/test( all| this),?(\s+|$)
  jstrachan/environment-jstrachan-v1-production:
    - agent: tekton
      always_run: true
      context: promotion-build
      name: promotion-build
      rerun_command: /test this
      trigger: (?m)^/test( all| this),?(\s+|$)
  jstrachan/environment-jstrachan-v1-staging:
    - agent: tekton
      always_run: true
      context: promotion-build
      name: promotion-build
      rerun_command: /test this
      trigger: (?m)^/test( all| this),?(\s+|$)
  jstrachan/godemo25:
    - agent: tekton
      always_run: true
      context: pr-build
      name: pr-build
      rerun_command: /test this
      trigger: (?m)^/test( all| this),?(\s+|$)
prowjob_namespace: jx
push_gateway: {}
tide:
  context_options:
    from-branch-protection: true
    required-if-present-contexts: null
    skip-unknown-contexts: false
  merge_method:
    jenkins-x/bdd-jx: merge
    jstrachan/environment-jstrachan-v1-production: merge
    jstrachan/environment-jstrachan-v1-staging: merge
    jstrachan/godemo25: merge
  queries:
    - labels:
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
      repos:
        - jenkins-x/bdd-jx
        - jstrachan/environment-jstrachan-v1-production
        - jstrachan/environment-jstrachan-v1-staging
        - jstrachan/godemo25
    - labels:
        - updatebot
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
      repos:
        - jenkins-x/bdd-jx
        - jstrachan/godemo25
  target_url: http://deck-jx.35.189.201.111.nip.io