// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/jenkins-x/lighthouse/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// LighthouseBreakpoints returns a LighthouseBreakpointInformer.
	LighthouseBreakpoints() LighthouseBreakpointInformer
	// LighthouseJobs returns a LighthouseJobInformer.
	LighthouseJobs() LighthouseJobInformer
	// LighthousePipelineSecurityPolicies returns a LighthousePipelineSecurityPolicyInformer.
	LighthousePipelineSecurityPolicies() LighthousePipelineSecurityPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// LighthouseBreakpoints returns a LighthouseBreakpointInformer.
func (v *version) LighthouseBreakpoints() LighthouseBreakpointInformer {
	return &lighthouseBreakpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LighthouseJobs returns a LighthouseJobInformer.
func (v *version) LighthouseJobs() LighthouseJobInformer {
	return &lighthouseJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LighthousePipelineSecurityPolicies returns a LighthousePipelineSecurityPolicyInformer.
func (v *version) LighthousePipelineSecurityPolicies() LighthousePipelineSecurityPolicyInformer {
	return &lighthousePipelineSecurityPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
