// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	lighthousev1alpha1 "github.com/jenkins-x/lighthouse/pkg/apis/lighthouse/v1alpha1"
	versioned "github.com/jenkins-x/lighthouse/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x/lighthouse/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jenkins-x/lighthouse/pkg/client/listers/lighthouse/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LighthouseJobInformer provides access to a shared informer and lister for
// LighthouseJobs.
type LighthouseJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.LighthouseJobLister
}

type lighthouseJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLighthouseJobInformer constructs a new informer for LighthouseJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLighthouseJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLighthouseJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLighthouseJobInformer constructs a new informer for LighthouseJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLighthouseJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LighthouseV1alpha1().LighthouseJobs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LighthouseV1alpha1().LighthouseJobs(namespace).Watch(options)
			},
		},
		&lighthousev1alpha1.LighthouseJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *lighthouseJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLighthouseJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *lighthouseJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&lighthousev1alpha1.LighthouseJob{}, f.defaultInformer)
}

func (f *lighthouseJobInformer) Lister() v1alpha1.LighthouseJobLister {
	return v1alpha1.NewLighthouseJobLister(f.Informer().GetIndexer())
}
