// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	lighthousev1alpha1 "github.com/jenkins-x/lighthouse/pkg/apis/lighthouse/v1alpha1"
	versioned "github.com/jenkins-x/lighthouse/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x/lighthouse/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jenkins-x/lighthouse/pkg/client/listers/lighthouse/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LighthouseBreakpointInformer provides access to a shared informer and lister for
// LighthouseBreakpoints.
type LighthouseBreakpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.LighthouseBreakpointLister
}

type lighthouseBreakpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLighthouseBreakpointInformer constructs a new informer for LighthouseBreakpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLighthouseBreakpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLighthouseBreakpointInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLighthouseBreakpointInformer constructs a new informer for LighthouseBreakpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLighthouseBreakpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LighthouseV1alpha1().LighthouseBreakpoints(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LighthouseV1alpha1().LighthouseBreakpoints(namespace).Watch(context.TODO(), options)
			},
		},
		&lighthousev1alpha1.LighthouseBreakpoint{},
		resyncPeriod,
		indexers,
	)
}

func (f *lighthouseBreakpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLighthouseBreakpointInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *lighthouseBreakpointInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&lighthousev1alpha1.LighthouseBreakpoint{}, f.defaultInformer)
}

func (f *lighthouseBreakpointInformer) Lister() v1alpha1.LighthouseBreakpointLister {
	return v1alpha1.NewLighthouseBreakpointLister(f.Informer().GetIndexer())
}
