apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: common
spec:
  pipelineSpec:
    tasks:
    - name: common
      taskSpec:
        steps:
        - image: common-image
          name: common-build
          env:
          - name: FOO
            value: foo
