apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  params:
    - name: BUILD_ID
      value: ""
    - name: JOB_NAME
      value: ""
    - name: JOB_SPEC
      value: ""
    - name: JOB_TYPE
      value: ""
    - name: PULL_BASE_REF
      value: ""
    - name: PULL_BASE_SHA
      value: ""
    - name: PULL_NUMBER
      value: ""
    - name: PULL_PULL_REF
      value: ""
    - name: PULL_PULL_SHA
      value: ""
    - name: PULL_REFS
      value: ""
    - name: REPO_NAME
      value: ""
    - name: REPO_OWNER
      value: ""
    - name: REPO_URL
      value: ""
  pipelineSpec:
    params:
      - description: the unique build number
        name: BUILD_ID
        type: string
      - description: the name of the job which is the trigger context name
        name: JOB_NAME
        type: string
      - description: the specification of the job
        name: JOB_SPEC
        type: string
      - description: '''the kind of job: postsubmit or presubmit'''
        name: JOB_TYPE
        type: string
      - description: the base git reference of the pull request
        name: PULL_BASE_REF
        type: string
      - description: the git sha of the base of the pull request
        name: PULL_BASE_SHA
        type: string
      - default: ""
        description: git pull request number
        name: PULL_NUMBER
        type: string
      - default: ""
        description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
        name: PULL_PULL_REF
        type: string
      - default: ""
        description: git revision to checkout (branch, tag, sha, ref…)
        name: PULL_PULL_SHA
        type: string
      - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
        name: PULL_REFS
        type: string
      - description: git repository name
        name: REPO_NAME
        type: string
      - description: git repository owner (user or organisation)
        name: REPO_OWNER
        type: string
      - description: git url to clone
        name: REPO_URL
        type: string
    tasks:
      - name: from-build-pack
        params:
          - name: BUILD_ID
            value: $(params.BUILD_ID)
          - name: JOB_NAME
            value: $(params.JOB_NAME)
          - name: JOB_SPEC
            value: $(params.JOB_SPEC)
          - name: JOB_TYPE
            value: $(params.JOB_TYPE)
          - name: PULL_BASE_REF
            value: $(params.PULL_BASE_REF)
          - name: PULL_BASE_SHA
            value: $(params.PULL_BASE_SHA)
          - name: PULL_NUMBER
            value: $(params.PULL_NUMBER)
          - name: PULL_PULL_REF
            value: $(params.PULL_PULL_REF)
          - name: PULL_PULL_SHA
            value: $(params.PULL_PULL_SHA)
          - name: PULL_REFS
            value: $(params.PULL_REFS)
          - name: REPO_NAME
            value: $(params.REPO_NAME)
          - name: REPO_OWNER
            value: $(params.REPO_OWNER)
          - name: REPO_URL
            value: $(params.REPO_URL)
        taskSpec:
          metadata: {}
          params:
            - description: the unique build number
              name: BUILD_ID
              type: string
            - description: the name of the job which is the trigger context name
              name: JOB_NAME
              type: string
            - description: the specification of the job
              name: JOB_SPEC
              type: string
            - description: '''the kind of job: postsubmit or presubmit'''
              name: JOB_TYPE
              type: string
            - description: the base git reference of the pull request
              name: PULL_BASE_REF
              type: string
            - description: the git sha of the base of the pull request
              name: PULL_BASE_SHA
              type: string
            - default: ""
              description: git pull request number
              name: PULL_NUMBER
              type: string
            - default: ""
              description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
              name: PULL_PULL_REF
              type: string
            - default: ""
              description: git revision to checkout (branch, tag, sha, ref…)
              name: PULL_PULL_SHA
              type: string
            - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
              name: PULL_REFS
              type: string
            - description: git repository name
              name: REPO_NAME
              type: string
            - description: git repository owner (user or organisation)
              name: REPO_OWNER
              type: string
            - description: git url to clone
              name: REPO_URL
              type: string
          spec: null
          stepTemplate:
            computeResources:
              requests:
                cpu: 400m
                memory: 512Mi
            env:
              - name: _JAVA_OPTIONS
                value: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
              - name: MAVEN_OPTS
                value: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
              - name: BUILD_ID
                value: $(params.BUILD_ID)
              - name: JOB_NAME
                value: $(params.JOB_NAME)
              - name: JOB_SPEC
                value: $(params.JOB_SPEC)
              - name: JOB_TYPE
                value: $(params.JOB_TYPE)
              - name: PULL_BASE_REF
                value: $(params.PULL_BASE_REF)
              - name: PULL_BASE_SHA
                value: $(params.PULL_BASE_SHA)
              - name: PULL_NUMBER
                value: $(params.PULL_NUMBER)
              - name: PULL_PULL_REF
                value: $(params.PULL_PULL_REF)
              - name: PULL_PULL_SHA
                value: $(params.PULL_PULL_SHA)
              - name: PULL_REFS
                value: $(params.PULL_REFS)
              - name: REPO_NAME
                value: $(params.REPO_NAME)
              - name: REPO_OWNER
                value: $(params.REPO_OWNER)
              - name: REPO_URL
                value: $(params.REPO_URL)
            volumeMounts:
              - mountPath: /root/.m2/
                name: maven-settings
              - mountPath: /root/.gnupg
                name: release-gpg
            workingDir: /workspace/source
          steps:
            - computeResources: {}
              image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.19.0
              name: git-clone
              script: |
                #!/bin/sh
                export SUBDIR="source"
                echo "git cloning url: $REPO_URL version $PULL_BASE_SHA to dir: $SUBDIR"
                git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
                git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
                git config --global credential.helper store
                git clone $REPO_URL $SUBDIR
                cd $SUBDIR
                git checkout $PULL_BASE_SHA
                echo "checked out revision: $PULL_BASE_SHA to dir: $SUBDIR"
              workingDir: /workspace
            - computeResources: {}
              image: gcr.io/jenkinsxio/jx-release-version:2.2.5
              name: next-version
              script: |
                #!/usr/bin/env sh
                jx-release-version > VERSION
            - computeResources: {}
              image: ghcr.io/jenkins-x/jx-boot:3.1.335
              name: jx-variables
              script: |
                #!/usr/bin/env sh
                jx gitops variables
            - computeResources: {}
              image: maven:3.6-openjdk-11
              name: build-mvn-deploy
              script: |
                #!/usr/bin/env bash
                source .jx/variables.sh

                # modify the pom.xml
                echo "upgrading the pom to version $VERSION"
                mvn versions:set -DnewVersion=$VERSION

                mvn --no-transfer-progress clean deploy
            - computeResources: {}
              image: gcr.io/jenkinsxio/jx-registry:0.0.11
              name: check-registry
            - computeResources: {}
              image: gcr.io/kaniko-project/executor:debug-v1.3.0
              name: build-container-build
              script: |
                #!/busybox/sh
                source .jx/variables.sh
                cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
                /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
            - computeResources: {}
              image: gcr.io/jenkinsxio/jx-changelog:0.0.34
              name: promote-changelog
              script: |
                #!/usr/bin/env sh
                source .jx/variables.sh

                if [ -d "charts/$REPO_NAME" ]; then
                sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
                sed -i -e "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" ./charts/$REPO_NAME/values.yaml
                sed -i -e "s/tag:.*/tag: $VERSION/" ./charts/$REPO_NAME/values.yaml;
                else echo no charts; fi

                jx changelog create --version v${VERSION}

                git add * || true
                git commit -a -m "chore: release $VERSION" --allow-empty
                git tag -fa v$VERSION -m "Release version $VERSION"
                git push --force origin v$VERSION
            - computeResources: {}
              image: ghcr.io/jenkins-x/jx-boot:3.1.335
              name: promote-helm-release
              script: |
                #!/usr/bin/env sh
                jx gitops helm release
            - computeResources: {}
              image: ghcr.io/jenkins-x/jx-promote:0.0.243
              name: promote-jx-promote
              script: |
                #!/usr/bin/env sh
                source .jx/variables.sh
                jx promote -b --all --timeout 1h --no-poll
          volumes:
            - name: maven-settings
              secret:
                secretName: jenkins-maven-settings
            - name: release-gpg
              secret:
                optional: true
                secretName: jenkins-release-gpg
          workspaces:
            - description: The git repo will be cloned onto the volume backing this workspace
              mountPath: /workspace
              name: output
        workspaces:
          - name: output
            workspace: output
    workspaces:
      - description: The git repo will be cloned onto the volume backing this workspace
        name: output
  taskRunTemplate:
    podTemplate: {}
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
  workspaces:
    - emptyDir: {}
      name: output
status: {}
