// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// LighthouseJobListerExpansion allows custom methods to be added to
// LighthouseJobLister.
type LighthouseJobListerExpansion interface{}

// LighthouseJobNamespaceListerExpansion allows custom methods to be added to
// LighthouseJobNamespaceLister.
type LighthouseJobNamespaceListerExpansion interface{}
