// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/jenkins-x/lighthouse/pkg/apis/lighthouse/v1alpha1"
	scheme "github.com/jenkins-x/lighthouse/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LighthousePipelineSecurityPoliciesGetter has a method to return a LighthousePipelineSecurityPolicyInterface.
// A group's client should implement this interface.
type LighthousePipelineSecurityPoliciesGetter interface {
	LighthousePipelineSecurityPolicies(namespace string) LighthousePipelineSecurityPolicyInterface
}

// LighthousePipelineSecurityPolicyInterface has methods to work with LighthousePipelineSecurityPolicy resources.
type LighthousePipelineSecurityPolicyInterface interface {
	Create(ctx context.Context, lighthousePipelineSecurityPolicy *v1alpha1.LighthousePipelineSecurityPolicy, opts v1.CreateOptions) (*v1alpha1.LighthousePipelineSecurityPolicy, error)
	Update(ctx context.Context, lighthousePipelineSecurityPolicy *v1alpha1.LighthousePipelineSecurityPolicy, opts v1.UpdateOptions) (*v1alpha1.LighthousePipelineSecurityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LighthousePipelineSecurityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LighthousePipelineSecurityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error)
	LighthousePipelineSecurityPolicyExpansion
}

// lighthousePipelineSecurityPolicies implements LighthousePipelineSecurityPolicyInterface
type lighthousePipelineSecurityPolicies struct {
	client rest.Interface
	ns     string
}

// newLighthousePipelineSecurityPolicies returns a LighthousePipelineSecurityPolicies
func newLighthousePipelineSecurityPolicies(c *LighthouseV1alpha1Client, namespace string) *lighthousePipelineSecurityPolicies {
	return &lighthousePipelineSecurityPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the lighthousePipelineSecurityPolicy, and returns the corresponding lighthousePipelineSecurityPolicy object, and an error if there is any.
func (c *lighthousePipelineSecurityPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	result = &v1alpha1.LighthousePipelineSecurityPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LighthousePipelineSecurityPolicies that match those selectors.
func (c *lighthousePipelineSecurityPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LighthousePipelineSecurityPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LighthousePipelineSecurityPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested lighthousePipelineSecurityPolicies.
func (c *lighthousePipelineSecurityPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a lighthousePipelineSecurityPolicy and creates it.  Returns the server's representation of the lighthousePipelineSecurityPolicy, and an error, if there is any.
func (c *lighthousePipelineSecurityPolicies) Create(ctx context.Context, lighthousePipelineSecurityPolicy *v1alpha1.LighthousePipelineSecurityPolicy, opts v1.CreateOptions) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	result = &v1alpha1.LighthousePipelineSecurityPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lighthousePipelineSecurityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a lighthousePipelineSecurityPolicy and updates it. Returns the server's representation of the lighthousePipelineSecurityPolicy, and an error, if there is any.
func (c *lighthousePipelineSecurityPolicies) Update(ctx context.Context, lighthousePipelineSecurityPolicy *v1alpha1.LighthousePipelineSecurityPolicy, opts v1.UpdateOptions) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	result = &v1alpha1.LighthousePipelineSecurityPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		Name(lighthousePipelineSecurityPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lighthousePipelineSecurityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the lighthousePipelineSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *lighthousePipelineSecurityPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *lighthousePipelineSecurityPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched lighthousePipelineSecurityPolicy.
func (c *lighthousePipelineSecurityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	result = &v1alpha1.LighthousePipelineSecurityPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("lighthousepipelinesecuritypolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
