// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/jenkins-x/lighthouse/pkg/apis/lighthouse/v1alpha1"
	scheme "github.com/jenkins-x/lighthouse/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LighthouseBreakpointsGetter has a method to return a LighthouseBreakpointInterface.
// A group's client should implement this interface.
type LighthouseBreakpointsGetter interface {
	LighthouseBreakpoints(namespace string) LighthouseBreakpointInterface
}

// LighthouseBreakpointInterface has methods to work with LighthouseBreakpoint resources.
type LighthouseBreakpointInterface interface {
	Create(ctx context.Context, lighthouseBreakpoint *v1alpha1.LighthouseBreakpoint, opts v1.CreateOptions) (*v1alpha1.LighthouseBreakpoint, error)
	Update(ctx context.Context, lighthouseBreakpoint *v1alpha1.LighthouseBreakpoint, opts v1.UpdateOptions) (*v1alpha1.LighthouseBreakpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LighthouseBreakpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LighthouseBreakpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LighthouseBreakpoint, err error)
	LighthouseBreakpointExpansion
}

// lighthouseBreakpoints implements LighthouseBreakpointInterface
type lighthouseBreakpoints struct {
	client rest.Interface
	ns     string
}

// newLighthouseBreakpoints returns a LighthouseBreakpoints
func newLighthouseBreakpoints(c *LighthouseV1alpha1Client, namespace string) *lighthouseBreakpoints {
	return &lighthouseBreakpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the lighthouseBreakpoint, and returns the corresponding lighthouseBreakpoint object, and an error if there is any.
func (c *lighthouseBreakpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LighthouseBreakpoint, err error) {
	result = &v1alpha1.LighthouseBreakpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LighthouseBreakpoints that match those selectors.
func (c *lighthouseBreakpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LighthouseBreakpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LighthouseBreakpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested lighthouseBreakpoints.
func (c *lighthouseBreakpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a lighthouseBreakpoint and creates it.  Returns the server's representation of the lighthouseBreakpoint, and an error, if there is any.
func (c *lighthouseBreakpoints) Create(ctx context.Context, lighthouseBreakpoint *v1alpha1.LighthouseBreakpoint, opts v1.CreateOptions) (result *v1alpha1.LighthouseBreakpoint, err error) {
	result = &v1alpha1.LighthouseBreakpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lighthouseBreakpoint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a lighthouseBreakpoint and updates it. Returns the server's representation of the lighthouseBreakpoint, and an error, if there is any.
func (c *lighthouseBreakpoints) Update(ctx context.Context, lighthouseBreakpoint *v1alpha1.LighthouseBreakpoint, opts v1.UpdateOptions) (result *v1alpha1.LighthouseBreakpoint, err error) {
	result = &v1alpha1.LighthouseBreakpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		Name(lighthouseBreakpoint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lighthouseBreakpoint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the lighthouseBreakpoint and deletes it. Returns an error if one occurs.
func (c *lighthouseBreakpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *lighthouseBreakpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched lighthouseBreakpoint.
func (c *lighthouseBreakpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LighthouseBreakpoint, err error) {
	result = &v1alpha1.LighthouseBreakpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("lighthousebreakpoints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
