apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: test
    context: "test"
    always_run: true
    optional: false
    trigger: "(?:/test|/retest)"
    rerun_command: "/retest"
    source: "test.yaml"
    pipeline_run_params:
      - name: MORNING_GREETINGS
        valueTemplate: "hey this is a custom parameter"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
  branchProtection:
    contexts:
    - test

