apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: lint
    context: "lint"
    always_run: true
    optional: false
    trigger: "(?:/lint|/relint)"
    rerun_command: "/relint"
    agent: tekton-pipeline

