apiVersion: tekton.dev/v1beta1
kind: CustomRun
metadata:
  name: myorg-myrepo-main-abc12-3-trigger-cleanup-fghij
status:
  startTime: "2024-01-15T10:00:00Z"
  conditions:
  - lastTransitionTime: "2024-01-15T10:00:00Z"
    message: Running custom task
    reason: Running
    status: Unknown
    type: Succeeded
