approve:
- lgtm_acts_as_approve: true
  repos:
  - someorg/somerepo
  require_self_approval: true
- repos:
  - myorg/myowner
  require_self_approval: false
cat: {}
cherry_pick_unapproved: {}
config_updater:
  gzip: false
  maps:
    env/prow/config.yaml:
      name: config
    env/prow/plugins.yaml:
      name: plugins
heart: {}
label:
  additional_labels: null
owners: {}
plugins:
  myorg/myowner:
  - approve
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  someorg/somerepo:
  - config-updater
  - approve
  - assign
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - cat
  - override
  - dog
  - pony
requiresig: {}
sigmention: {}
size:
  l: 0
  m: 0
  s: 0
  xl: 0
  xxl: 0
slack: {}
triggers:
- repos:
  - someorg/somerepo
  - myorg/myowner
  trusted_org: someorg