// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/jenkins-x/lighthouse/pkg/client/clientset/versioned/typed/lighthouse/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeLighthouseV1alpha1 struct {
	*testing.Fake
}

func (c *FakeLighthouseV1alpha1) LighthouseJobs(namespace string) v1alpha1.LighthouseJobInterface {
	return &FakeLighthouseJobs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeLighthouseV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
