// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/jenkins-x/lighthouse/pkg/apis/lighthouse/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLighthousePipelineSecurityPolicies implements LighthousePipelineSecurityPolicyInterface
type FakeLighthousePipelineSecurityPolicies struct {
	Fake *FakeLighthouseV1alpha1
	ns   string
}

var lighthousepipelinesecuritypoliciesResource = schema.GroupVersionResource{Group: "lighthouse.jenkins.io", Version: "v1alpha1", Resource: "lighthousepipelinesecuritypolicies"}

var lighthousepipelinesecuritypoliciesKind = schema.GroupVersionKind{Group: "lighthouse.jenkins.io", Version: "v1alpha1", Kind: "LighthousePipelineSecurityPolicy"}

// Get takes name of the lighthousePipelineSecurityPolicy, and returns the corresponding lighthousePipelineSecurityPolicy object, and an error if there is any.
func (c *FakeLighthousePipelineSecurityPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(lighthousepipelinesecuritypoliciesResource, c.ns, name), &v1alpha1.LighthousePipelineSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthousePipelineSecurityPolicy), err
}

// List takes label and field selectors, and returns the list of LighthousePipelineSecurityPolicies that match those selectors.
func (c *FakeLighthousePipelineSecurityPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LighthousePipelineSecurityPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(lighthousepipelinesecuritypoliciesResource, lighthousepipelinesecuritypoliciesKind, c.ns, opts), &v1alpha1.LighthousePipelineSecurityPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LighthousePipelineSecurityPolicyList{ListMeta: obj.(*v1alpha1.LighthousePipelineSecurityPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.LighthousePipelineSecurityPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lighthousePipelineSecurityPolicies.
func (c *FakeLighthousePipelineSecurityPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(lighthousepipelinesecuritypoliciesResource, c.ns, opts))

}

// Create takes the representation of a lighthousePipelineSecurityPolicy and creates it.  Returns the server's representation of the lighthousePipelineSecurityPolicy, and an error, if there is any.
func (c *FakeLighthousePipelineSecurityPolicies) Create(ctx context.Context, lighthousePipelineSecurityPolicy *v1alpha1.LighthousePipelineSecurityPolicy, opts v1.CreateOptions) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(lighthousepipelinesecuritypoliciesResource, c.ns, lighthousePipelineSecurityPolicy), &v1alpha1.LighthousePipelineSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthousePipelineSecurityPolicy), err
}

// Update takes the representation of a lighthousePipelineSecurityPolicy and updates it. Returns the server's representation of the lighthousePipelineSecurityPolicy, and an error, if there is any.
func (c *FakeLighthousePipelineSecurityPolicies) Update(ctx context.Context, lighthousePipelineSecurityPolicy *v1alpha1.LighthousePipelineSecurityPolicy, opts v1.UpdateOptions) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(lighthousepipelinesecuritypoliciesResource, c.ns, lighthousePipelineSecurityPolicy), &v1alpha1.LighthousePipelineSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthousePipelineSecurityPolicy), err
}

// Delete takes name of the lighthousePipelineSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *FakeLighthousePipelineSecurityPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(lighthousepipelinesecuritypoliciesResource, c.ns, name), &v1alpha1.LighthousePipelineSecurityPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLighthousePipelineSecurityPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(lighthousepipelinesecuritypoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LighthousePipelineSecurityPolicyList{})
	return err
}

// Patch applies the patch and returns the patched lighthousePipelineSecurityPolicy.
func (c *FakeLighthousePipelineSecurityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LighthousePipelineSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(lighthousepipelinesecuritypoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.LighthousePipelineSecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthousePipelineSecurityPolicy), err
}
