// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/jenkins-x/lighthouse/pkg/apis/lighthouse/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLighthouseBreakpoints implements LighthouseBreakpointInterface
type FakeLighthouseBreakpoints struct {
	Fake *FakeLighthouseV1alpha1
	ns   string
}

var lighthousebreakpointsResource = schema.GroupVersionResource{Group: "lighthouse.jenkins.io", Version: "v1alpha1", Resource: "lighthousebreakpoints"}

var lighthousebreakpointsKind = schema.GroupVersionKind{Group: "lighthouse.jenkins.io", Version: "v1alpha1", Kind: "LighthouseBreakpoint"}

// Get takes name of the lighthouseBreakpoint, and returns the corresponding lighthouseBreakpoint object, and an error if there is any.
func (c *FakeLighthouseBreakpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LighthouseBreakpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(lighthousebreakpointsResource, c.ns, name), &v1alpha1.LighthouseBreakpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthouseBreakpoint), err
}

// List takes label and field selectors, and returns the list of LighthouseBreakpoints that match those selectors.
func (c *FakeLighthouseBreakpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LighthouseBreakpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(lighthousebreakpointsResource, lighthousebreakpointsKind, c.ns, opts), &v1alpha1.LighthouseBreakpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LighthouseBreakpointList{ListMeta: obj.(*v1alpha1.LighthouseBreakpointList).ListMeta}
	for _, item := range obj.(*v1alpha1.LighthouseBreakpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lighthouseBreakpoints.
func (c *FakeLighthouseBreakpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(lighthousebreakpointsResource, c.ns, opts))

}

// Create takes the representation of a lighthouseBreakpoint and creates it.  Returns the server's representation of the lighthouseBreakpoint, and an error, if there is any.
func (c *FakeLighthouseBreakpoints) Create(ctx context.Context, lighthouseBreakpoint *v1alpha1.LighthouseBreakpoint, opts v1.CreateOptions) (result *v1alpha1.LighthouseBreakpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(lighthousebreakpointsResource, c.ns, lighthouseBreakpoint), &v1alpha1.LighthouseBreakpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthouseBreakpoint), err
}

// Update takes the representation of a lighthouseBreakpoint and updates it. Returns the server's representation of the lighthouseBreakpoint, and an error, if there is any.
func (c *FakeLighthouseBreakpoints) Update(ctx context.Context, lighthouseBreakpoint *v1alpha1.LighthouseBreakpoint, opts v1.UpdateOptions) (result *v1alpha1.LighthouseBreakpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(lighthousebreakpointsResource, c.ns, lighthouseBreakpoint), &v1alpha1.LighthouseBreakpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthouseBreakpoint), err
}

// Delete takes name of the lighthouseBreakpoint and deletes it. Returns an error if one occurs.
func (c *FakeLighthouseBreakpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(lighthousebreakpointsResource, c.ns, name), &v1alpha1.LighthouseBreakpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLighthouseBreakpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(lighthousebreakpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LighthouseBreakpointList{})
	return err
}

// Patch applies the patch and returns the patched lighthouseBreakpoint.
func (c *FakeLighthouseBreakpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LighthouseBreakpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(lighthousebreakpointsResource, c.ns, name, pt, data, subresources...), &v1alpha1.LighthouseBreakpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LighthouseBreakpoint), err
}
