apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cheese
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml@1d39235ee9235d7d52d4025a8e59cb8bda04306a
        steps:
        - name: jx-variables
        - image: uses:https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/1d39235ee9235d7d52d4025a8e59cb8bda04306a/packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml
          name: build-npm-install
        - name: build-npm-test
        - name: build-container-build
        - name: promote-jx-preview
        - name: promote-release
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx updatebot argo promote --target-git-url https://github.com/myorg/my-staging-repo

