apiVersion: v1
kind: ConfigMap
metadata:
  name: lighthouse-external-plugins
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
data:
  config.yaml: |-
{{ toYaml .Values.externalPlugins | indent 4 }}
