---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ template "foghorn.name" . }}-cluster-scoped
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ template "foghorn.name" . }}-cluster-scoped
subjects:
    - kind: ServiceAccount
      name: {{ template "foghorn.name" . }}
      namespace: {{ .Release.Namespace }}
