---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "foghorn.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
