{{- if .Values.poller.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "poller.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "poller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "poller.name" . }}
{{- end }}
