{{- if .Values.engines.tekton }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tektoncontroller.name" . }}-cluster-scoped
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - list
  - get
  - watch
- apiGroups:
  - lighthouse.jenkins.io
  resources:
  - lighthousebreakpoints
  - lighthousejobs
  verbs:
  - get
  - update
  - list
  - watch
- apiGroups:
  - lighthouse.jenkins.io
  resources:
  - lighthousejobs/status
  verbs:
  - update
  - get
  - watch
  - patch
{{- end }}
