{{- if .Values.engines.tekton }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tektoncontroller.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "tektoncontroller.name" . }}-cluster-scoped
subjects:
  - kind: ServiceAccount
    name: {{ template "tektoncontroller.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
