---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "webhooks.name" . }}-cluster-scoped
rules:
- apiGroups:
  - lighthouse.jenkins.io
  resources:
  - lighthousejobs
  verbs:
  - create
  - delete
  - list
  - update
  - get
  - watch
  - patch
- apiGroups:
  - lighthouse.jenkins.io
  resources:
  - lighthousejobs/status
  verbs:
  - create
  - delete
  - list
  - update
  - get
  - watch
  - patch

