apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: cheese
spec:
  params:
    - name: REPO_URL
      value: ""
    - name: PULL_PULL_SHA
      value: master
    - name: subdirectory
      value: source
    - name: BUILD_ID
      value: ""
    - name: JOB_NAME
      value: ""
    - name: JOB_SPEC
      value: ""
    - name: JOB_TYPE
      value: ""
    - name: PULL_BASE_REF
      value: master
    - name: PULL_BASE_SHA
      value: ""
    - name: PULL_NUMBER
      value: ""
    - name: PULL_PULL_REF
      value: ""
    - name: PULL_REFS
      value: ""
    - name: REPO_NAME
      value: ""
    - name: REPO_OWNER
      value: ""
  pipelineSpec:
    params:
      - description: git url to clone
        name: REPO_URL
        type: string
      - default: master
        description: git revision to checkout (branch, tag, sha, ref…)
        name: PULL_PULL_SHA
        type: string
      - default: source
        description: subdirectory inside of /workspace to clone the git repo
        name: subdirectory
        type: string
      - description: the unique build number
        name: BUILD_ID
        type: string
      - description: the name of the job which is the trigger context name
        name: JOB_NAME
        type: string
      - description: the specification of the job
        name: JOB_SPEC
        type: string
      - description: 'the kind of job: postsubmit or presubmit'
        name: JOB_TYPE
        type: string
      - default: master
        description: the base git reference of the pull request
        name: PULL_BASE_REF
        type: string
      - description: the git sha of the base of the pull request
        name: PULL_BASE_SHA
        type: string
      - default: ""
        description: git pull request number
        name: PULL_NUMBER
        type: string
      - default: ""
        description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
        name: PULL_PULL_REF
        type: string
      - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
        name: PULL_REFS
        type: string
      - description: git repository name
        name: REPO_NAME
        type: string
      - description: git repository owner (user or organisation)
        name: REPO_OWNER
        type: string
    tasks:
      - name: cheese
        params:
          - name: REPO_URL
            value: $(params.REPO_URL)
          - name: PULL_PULL_SHA
            value: $(params.PULL_PULL_SHA)
          - name: subdirectory
            value: $(params.subdirectory)
          - name: BUILD_ID
            value: $(params.BUILD_ID)
          - name: JOB_NAME
            value: $(params.JOB_NAME)
          - name: JOB_SPEC
            value: $(params.JOB_SPEC)
          - name: JOB_TYPE
            value: $(params.JOB_TYPE)
          - name: PULL_BASE_REF
            value: $(params.PULL_BASE_REF)
          - name: PULL_BASE_SHA
            value: $(params.PULL_BASE_SHA)
          - name: PULL_NUMBER
            value: $(params.PULL_NUMBER)
          - name: PULL_PULL_REF
            value: $(params.PULL_PULL_REF)
          - name: PULL_REFS
            value: $(params.PULL_REFS)
          - name: REPO_NAME
            value: $(params.REPO_NAME)
          - name: REPO_OWNER
            value: $(params.REPO_OWNER)
        taskSpec:
          metadata: {}
          params:
            - description: git url to clone
              name: REPO_URL
              type: string
            - default: master
              description: git revision to checkout (branch, tag, sha, ref…)
              name: PULL_PULL_SHA
              type: string
            - default: source
              description: subdirectory inside of /workspace to clone the git repo
              name: subdirectory
              type: string
            - description: the unique build number
              name: BUILD_ID
              type: string
            - description: the name of the job which is the trigger context name
              name: JOB_NAME
              type: string
            - description: the specification of the job
              name: JOB_SPEC
              type: string
            - description: 'the kind of job: postsubmit or presubmit'
              name: JOB_TYPE
              type: string
            - default: master
              description: the base git reference of the pull request
              name: PULL_BASE_REF
              type: string
            - description: the git sha of the base of the pull request
              name: PULL_BASE_SHA
              type: string
            - default: ""
              description: git pull request number
              name: PULL_NUMBER
              type: string
            - default: ""
              description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
              name: PULL_PULL_REF
              type: string
            - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
              name: PULL_REFS
              type: string
            - description: git repository name
              name: REPO_NAME
              type: string
            - description: git repository owner (user or organisation)
              name: REPO_OWNER
              type: string
          spec: null
          stepTemplate:
            computeResources:
              requests:
                cpu: 400m
                memory: 512Mi
            env:
              - name: BUILD_ID
                value: $(params.BUILD_ID)
              - name: JOB_NAME
                value: $(params.JOB_NAME)
              - name: JOB_SPEC
                value: $(params.JOB_SPEC)
              - name: JOB_TYPE
                value: $(params.JOB_TYPE)
              - name: PULL_BASE_REF
                value: $(params.PULL_BASE_REF)
              - name: PULL_BASE_SHA
                value: $(params.PULL_BASE_SHA)
              - name: PULL_NUMBER
                value: $(params.PULL_NUMBER)
              - name: PULL_PULL_REF
                value: $(params.PULL_PULL_REF)
              - name: PULL_PULL_SHA
                value: $(params.PULL_PULL_SHA)
              - name: PULL_REFS
                value: $(params.PULL_REFS)
              - name: REPO_NAME
                value: $(params.REPO_NAME)
              - name: REPO_OWNER
                value: $(params.REPO_OWNER)
              - name: REPO_URL
                value: $(params.REPO_URL)
            volumeMounts:
              - mountPath: /home/jenkins
                name: workspace-volume
              - mountPath: /etc/podinfo
                name: podinfo
                readOnly: true
            workingDir: /workspace/source
          steps:
            - args:
                - -c
                - 'mkdir -p $HOME; git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}; git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}; git config --global credential.helper store; git clone $(params.REPO_URL) $(params.subdirectory); echo cloned url: $(params.REPO_URL) to dir: $(params.subdirectory); cd $(params.subdirectory); git checkout $(params.PULL_PULL_SHA); echo checked out revision: $(params.PULL_PULL_SHA) to dir: $(params.subdirectory)'
              command:
                - /bin/sh
              computeResources: {}
              image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
              name: git-clone
              workingDir: /workspace
            - args:
                - gitops
                - git
                - setup
                - --namespace
                - jx-git-operator
              command:
                - jx
              computeResources: {}
              image: gcr.io/jenkinsxio/jx-cli:latest
              name: git-setup
              workingDir: /workspace
            - args:
                - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
              command:
                - /bin/sh
                - -c
              computeResources: {}
              image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
              name: setup-builder-home
            - args:
                - step
                - git
                - merge
                - --verbose
                - --baseSHA
                - $(params.PULL_BASE_SHA)
                - --sha
                - $(params.PULL_PULL_SHA)
                - --baseBranch
                - $(params.PULL_BASE_REF)
              command:
                - jx
              computeResources: {}
              image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
              name: git-merge
            - args:
                - gitops
                - variables
              command:
                - jx
              computeResources: {}
              image: gcr.io/jenkinsxio/jx-cli:latest
              name: jx-variables
            - args:
                - jx step credential -s npm-token -k file -f /builder/home/.npmrc --optional=true
              command:
                - /bin/sh
                - -c
              computeResources: {}
              image: gcr.io/jenkinsxio/builder-nodejs:2.1.150-769
              name: build-npmrc
            - args:
                - npm install
              command:
                - /bin/sh
                - -c
              computeResources: {}
              image: gcr.io/jenkinsxio/builder-nodejs:2.1.150-769
              name: build-npm-install
            - args:
                - CI=true DISPLAY=:99 npm test
              command:
                - /bin/sh
                - -c
              computeResources: {}
              image: gcr.io/jenkinsxio/builder-nodejs:2.1.150-769
              name: build-npm-test
            - args:
                - source .jx/variables.sh && cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json && /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
              command:
                - /busybox/sh
                - -c
              computeResources: {}
              image: gcr.io/jenkinsxio/kaniko:0.0.5
              name: build-container-build
            - args:
                - source /workspace/source/.jx/variables.sh && jx preview create
              command:
                - /bin/bash
                - -c
              computeResources: {}
              image: gcr.io/jenkinsxio/jx-cli:latest
              name: promote-jx-preview
          volumes:
            - emptyDir: {}
              name: workspace-volume
            - downwardAPI:
                items:
                  - fieldRef:
                      fieldPath: metadata.labels
                    path: labels
              name: podinfo
  taskRunTemplate: {}
  timeouts:
    pipeline: 24h0m0s
status: {}
