apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        sidecars:
        - image: xyz/json-server:0.1.15
          name: "json-server"
          resources: {}
          script: |
            #!/bin/ash
            while [ ! -f /workspace/source/JsonServer/mocks.json ] ; do
              echo "Waiting for mocks.json"
              sleep 1
            done
            json-server --watch /workspace/source/JsonServer/mocks.json
          workspaces:
          - name: source
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/packs/javascript/.lighthouse/jenkins-x/pullrequest.yaml@1d39235ee9235d7d52d4025a8e59cb8bda04306a
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - image: node:14-slim
        - name: build-npm-test
          resources: {}
          script: |
            #!/bin/sh
            yarn install
            CI=true DISPLAY=:99 yarn run test:unit
        workspaces:
        - name: source
      workspaces:
      - name: source
        workspace: source
    workspaces:
    - name: source
  podTemplate: {}
  workspaces:
  - {name: source, emptyDir: {}}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}